### ISSUE TITLE
feature:install project-base-karaf return error 

### ISSUE THREAD

**Issue by chc7042** [vaadin/base-starter-flow-karaf#19]
Hi All when i tried to feature:install then i had met a problem as below

karaf@root()> feature:install project-base-karaf
org.apache.felix.resolver.reason.ReasonException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=project-base-karaf; type=karaf.feature; version="[1.0.0.SNAPSHOT,1.0.0.SNAPSHOT]"; filter:="(&(osgi.identity=project-base-karaf)(type=karaf.feature)(version>=1.0.0.SNAPSHOT)(version<=1.0.0.SNAPSHOT))" [caused by: Unable to resolve project-base-karaf/1.0.0.SNAPSHOT: missing requirement [project-base-karaf/1.0.0.SNAPSHOT] osgi.identity; osgi.identity=project-base-karaf; type=osgi.bundle; version="[1.0.0.202103170445,1.0.0.202103170445]"; resolution:=mandatory [caused by: Unable to resolve project-base-karaf/1.0.0.202103170445: missing requirement [project-base-karaf/1.0.0.202103170445] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.osgi.framework)(version>=1.9.0)(!(version>=2.0.0)))"]]
        at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1343)
        at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:392)
        at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:378)
        at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:332)
        at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:257)
        at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:401)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1063)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:998)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve project-base-karaf/1.0.0.SNAPSHOT: missing requirement [project-base-karaf/1.0.0.SNAPSHOT] osgi.identity; osgi.identity=project-base-karaf; type=osgi.bundle; version="[1.0.0.202103170445,1.0.0.202103170445]"; resolution:=mandatory [caused by: Unable to resolve project-base-karaf/1.0.0.202103170445: missing requirement [project-base-karaf/1.0.0.202103170445] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.osgi.framework)(version>=1.9.0)(!(version>=2.0.0)))"]
        at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1343)
        ... 12 more
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve project-base-karaf/1.0.0.202103170445: missing requirement [project-base-karaf/1.0.0.202103170445] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.osgi.framework)(version>=1.9.0)(!(version>=2.0.0)))"
        at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1343)
        ... 13 more
Error executing command: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=project-base-karaf; type=karaf.feature; version="[1.0.0.SNAPSHOT,1.0.0.SNAPSHOT]"; filter:="(&(osgi.identity=project-base-karaf)(type=karaf.feature)(version>=1.0.0.SNAPSHOT)(version<=1.0.0.SNAPSHOT))" [caused by: Unable to resolve project-base-karaf/1.0.0.SNAPSHOT: missing requirement [project-base-karaf/1.0.0.SNAPSHOT] osgi.identity; osgi.identity=project-base-karaf; type=osgi.bundle; version="[1.0.0.202103170445,1.0.0.202103170445]"; resolution:=mandatory [caused by: Unable to resolve project-base-karaf/1.0.0.202103170445: missing requirement [project-base-karaf/1.0.0.202103170445] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.osgi.framework)(version>=1.9.0)(!(version>=2.0.0)))"]]

do you have an idea about this?

**Comment by chc7042** [comment]
Hi All
i tried to mvn install to install project artifact and mvn -pl starter install -Prun directly without karaf setting. but result is same.
![image](https://user-images.githubusercontent.com/2008984/111554694-1fb48580-87ca-11eb-8971-c4d4047ae37a.png)

how can i solve this problem? i already look into port of localhost but here is no restriction please help me

**Comment by chc7042** [comment]
i did change java version to 11 but error message same.. anybody help me

**Comment by mstahv** [comment]
Did you get this resolved? Are you trying the example in www.gitpod.io ? I have never tried that.

**Comment by Maurice-Betzel** [comment]
Works fine for me on local windows machine using OpenJdk 8 64 bits.
Even added service access from external view works, manual push over websocket works even in external view.

**Comment by denis-anisimov** [comment]
This :
```
osgi.wiring.package=org.osgi.framework)(version>=1.9.0)(!(version>=2.0.0)))
```
says that project requires OSGi version `1.9` but this can't be with the current project since all dependencies declare R7 OSGi spec (`1.7` ) version. Ot means that the project is somehow modified to use R9 OSGi spec and Karaf doesn't support it.
