### ISSUE TITLE
Starting help-view bundle navigates application to invalid URL

### ISSUE THREAD

**Issue by edler-san** [vaadin/base-starter-flow-karaf#36]
Activating the help-view bundle in Karaf results in a navigation to a non-existing URL.
![image](https://user-images.githubusercontent.com/19165931/114539823-27463d80-9c55-11eb-89a2-a2e75f0412db.png)

After navigating back the application and new view work as expected.

Stacktrace from Karaf is:
`2021-04-13T11:23:56,164 | ERROR | pool-6-thread-1  | DefaultErrorHandler              | 168 - com.vaadin.flow.server - 6.0.5 | 
java.util.concurrent.ExecutionException: com.vaadin.flow.router.NotFoundException: No route found for the given navigation target and parameters!
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_181]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_181]
	at com.vaadin.flow.server.FutureAccess.get(FutureAccess.java:62) ~[?:?]
	at com.vaadin.flow.server.VaadinService.runPendingAccessTasks(VaadinService.java:2053) ~[?:?]
	at com.vaadin.flow.server.VaadinSession.unlock(VaadinSession.java:681) ~[?:?]
	at com.vaadin.flow.server.VaadinService.ensureAccessQueuePurged(VaadinService.java:2016) ~[?:?]
	at com.vaadin.flow.server.VaadinService.accessSession(VaadinService.java:1983) ~[?:?]
	at com.vaadin.flow.server.VaadinSession.access(VaadinSession.java:969) ~[?:?]
	at com.vaadin.flow.component.UI.access(UI.java:518) ~[?:?]
	at com.vaadin.flow.component.UI.access(UI.java:501) ~[?:?]
	at com.example.starter.base.impl.MainLayout.lambda$onAttach$6f4ab3e5$1(MainLayout.java:105) ~[?:?]
	at com.vaadin.flow.router.internal.AbstractRouteRegistry.lambda$fireEvent$2(AbstractRouteRegistry.java:159) ~[?:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891) ~[?:1.8.0_181]
	at com.vaadin.flow.router.internal.AbstractRouteRegistry.fireEvent(AbstractRouteRegistry.java:159) ~[?:?]
	at com.vaadin.flow.server.SessionRouteRegistry.lambda$addRoutesChangeListener$4d208e45$1(SessionRouteRegistry.java:135) ~[?:?]
	at com.vaadin.flow.router.internal.AbstractRouteRegistry.lambda$fireEvent$2(AbstractRouteRegistry.java:159) ~[?:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891) ~[?:1.8.0_181]
	at com.vaadin.flow.router.internal.AbstractRouteRegistry.fireEvent(AbstractRouteRegistry.java:159) ~[?:?]
	at com.vaadin.flow.router.internal.AbstractRouteRegistry.unlock(AbstractRouteRegistry.java:140) ~[?:?]
	at com.vaadin.flow.router.internal.AbstractRouteRegistry.configure(AbstractRouteRegistry.java:100) ~[?:?]
	at com.vaadin.flow.router.internal.AbstractRouteRegistry.removeRoute(AbstractRouteRegistry.java:330) ~[?:?]
	at com.vaadin.flow.server.startup.RouteRegistryInitializer.lambda$removePreviousRoutes$2(RouteRegistryInitializer.java:100) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_181]
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080) ~[?:1.8.0_181]
	at com.vaadin.flow.server.startup.RouteRegistryInitializer.removePreviousRoutes(RouteRegistryInitializer.java:99) ~[?:?]
	at com.vaadin.flow.server.startup.RouteRegistryInitializer.initialize(RouteRegistryInitializer.java:58) ~[?:?]
	at com.vaadin.flow.server.startup.VaadinServletContextStartupInitializer.process(VaadinServletContextStartupInitializer.java:41) ~[?:?]
	at com.vaadin.flow.osgi.support.ServletContainerInitializerClasses.handleTypes(ServletContainerInitializerClasses.java:245) ~[?:?]
	at com.vaadin.flow.osgi.support.ServletContainerInitializerClasses.lambda$resetContextInitializers$1(ServletContainerInitializerClasses.java:228) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_181]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_181]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_181]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_181]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_181]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_181]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_181]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_181]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_181]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_181]
	at com.vaadin.flow.osgi.support.ServletContainerInitializerClasses.resetContextInitializers(ServletContainerInitializerClasses.java:228) ~[?:?]
	at com.vaadin.flow.osgi.support.ServletContainerInitializerClasses.addScannedClasses(ServletContainerInitializerClasses.java:153) ~[?:?]
	at com.vaadin.flow.osgi.support.VaadinBundleTracker.scanActivatedBundle(VaadinBundleTracker.java:121) ~[?:?]
	at com.vaadin.flow.osgi.support.VaadinBundleTracker.lambda$addingBundle$0(VaadinBundleTracker.java:82) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: com.vaadin.flow.router.NotFoundException: No route found for the given navigation target and parameters!
	at com.vaadin.flow.router.RouteConfiguration.getUrl(RouteConfiguration.java:512) ~[?:?]
	at com.vaadin.flow.component.UI.navigate(UI.java:900) ~[?:?]
	at com.vaadin.flow.component.UI.navigate(UI.java:868) ~[?:?]
	at com.example.starter.base.impl.MainLayout.lambda$onAttach$52ea40de$1(MainLayout.java:108) ~[?:?]
	at com.vaadin.flow.component.UI.accessSynchronously(UI.java:446) ~[?:?]
	at com.vaadin.flow.component.UI.access$000(UI.java:97) ~[?:?]
	at com.vaadin.flow.component.UI$2.execute(UI.java:521) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
	at com.vaadin.flow.server.VaadinService.runPendingAccessTasks(VaadinService.java:2050) ~[?:?]
	... 42 more
`

**Comment by denis-anisimov** [comment]
The root cause is route handling in flow: https://github.com/vaadin/flow/issues/10636
